
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.luminousworld]
			yellow_birch = true

		[types.leaves_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true
			palo_verde = true
			araucaria = true
			ripe_baobab = true
			flowering_baobab = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			ripe_orchard = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			yucca = true
			ripe_yucca = true
			flowering_yucca = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			silver_maple = true
			green_apple_skyris = true
			flowering_skyris = true
			flowering_ironwood = true
			white_sakura = true
			yellow_sakura = true
			yellow_birch = true
			yellow_spruce = true
			firecracker = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.luminous_depths]
			indiwo = true

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.tardis_refined]
			ars = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.bloomingnature]
			larch = true
			baobab = true
			orange = true
			swamp_oak = true
			aspen = true
			fan_palm = true
			swamp_cypress = true
			ebony = true
			chestnut = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.croptopia]
			cinnamon = true

		[types.leaves_type.scpo]
			scp_143 = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.phantasm]
			pream = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			purple_glacia = true
			gilded_oak = true
			blighted_skyroot = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.betternether]
			willow = true
			rubeus = true
			anchor_tree = true
			nether_sakura = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

	[types.wood_type]

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.biomeswevegone]
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			fir = true
			florus = true
			green_enchanted = true
			holly = true
			ironwood = true
			jacaranda = true
			mahogany = true
			maple = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			sakura = true
			skyris = true
			white_mangrove = true
			willow = true
			witch_hazel = true
			zelkova = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.luminous_depths]
			indiwo = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.bloomingnature]
			larch = true
			baobab = true
			swamp_oak = true
			aspen = true
			fan_palm = true
			fir = true
			swamp_cypress = true
			ebony = true
			chestnut = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.scpo]
			scp_143 = true

		[types.wood_type.mysticsbiomes]
			strawberry = true
			cherry = true
			peach = true
			maple = true
			sea_foam = true
			tropical = true
			jacaranda = true

		[types.wood_type.luphieclutteredmod]
			luphie_flowering_pink = true
			luphie_yellow = true
			luphie_flowering_yellow = true
			luphie_green = true
			luphie_glow = true
			luphie_purple = true
			luphie_flowering_purple = true
			luphie_pink = true

		[types.wood_type.phantasm]
			pream = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.betternether]
			nether_reed = true
			stalagnate = true
			willow = true
			wart = true
			rubeus = true
			mushroom_fir = true
			nether_mushroom = true
			anchor_tree = true
			nether_sakura = true

		[types.wood_type.betterend]
			mossy_glowshroom = true
			pythadendron = true
			end_lotus = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			helix_tree = true
			umbrella_tree = true
			jellyshroom = true
			lucernia = true

	[types.cake]

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

		[types.cake.ubesdelight]
			ube_cake = true

		[types.cake.mysticsbiomes]
			strawberry_cake = true
			vanilla_cake = true
			chocolate_cake = true
			pink_frosted_cake = true
			orange_frosted_cake = true
			yellow_frosted_cake = true
			lime_frosted_cake = true
			cyan_frosted_cake = true
			purple_frosted_cake = true

		[types.cake.createfood]
			cake_chorus_fruit = true
			cake_glow_berry = true
			berry_cream_cake_sweet_berry = true
			berry_cream_cake_chorus_fruit = true
			berry_cream_cake_glow_berry = true
			chorus_fruit_cream_cake_sweet_berry = true
			chorus_fruit_cream_cake_chorus_fruit = true
			chorus_fruit_cream_cake_glow_berry = true
			glow_berry_cream_cake_sweet_berry = true
			glow_berry_cream_cake_chorus_fruit = true
			glow_berry_cream_cake_glow_berry = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

		[entries.wood_type.friendsandfoes]
			beehive = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			dining_bench = true
			drawer = true
			side_table = true
			couch = true
			table = true
			chair = true
			shelf = true
			cupboard = true
			bench = true
			pillar_trim = true
			nightstand = true

		[entries.wood_type.furnish]
			coffin = true
			cabinet = true
			kitchen_cabinet = true
			log_bench = true
			shelf = true
			bench = true
			shutter = true
			bedside_table = true
			square_table = true
			wardrobe = true
			stool = true
			bookshelf_chest = true
			pedestal_table = true
			ladder = true
			crate = true
			table = true
			chair = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			end_table = true
			stool_chair = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.another_furniture]
			flower_box = true
			shutter = true
			drawer = true
			shelf = true
			bench = true
			table = true
			chair = true

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			desk = true
			cutting_board = true
			drawer = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			kitchen_cabinetry = true
			crate = true
			chair = true
			light_ceiling_fan = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.refurbished_furniture]
			hedge = true

